sudo: required
language: python
cache: pip
python:
- '3.6'

services:
- docker

env:
  global:
  #- LANG="C.UTF-8"
  #- LC_ALL="C"
  - LC_ALL=en_US.UTF-8
  - LANG=en_US.UTF-8
  - FORMULA_REV=nightly
  - PIPENV_SHELL_COMPAT=true PIPENV_COLORBLIND=true PIPENV_NOSPIN=true
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: ng2Wu+1oMndftfY+IpQP2BhfuivnmiL1VvEKpqb/lul1cWrJMTDciXKisXhZclo9IdoVEzwRg49tNMJBMWn+zxWaVR9CHuvOKY0BsFofc6jY6k9KXUreSpQfcvuSOb/Iy0BLZqxPE3qSM/Y94uIMC4yar582TXi+ObP/PdBj+bL/vr8AXd9dm69rXUeKHH1/3unf8FZI0riErGN0EPcWjUIXqxPIM8bAFMG0QLtULGe9qHO9KigLHD/FNPCQK50Z3EPRG4znDbSgcgrT5SpQXW6BUMMTYHQo/sKunR0n/3SkzLuY3ufljpPH/3cNtYvWZ7fMz7zYtpRe12Fr/BAJEk/vgcUmG8eglq18ePIN3Nhfbo0DMLrwDsMGILjk3jBuemKO5NxVlmP+tKcoXN85W0q0kbs8n1VP1hJ/d5+MfTWyLg++OL0D3+jVmQcKb5YVdKAy53ONMFH+hrr3Z+DHJT2jbVaTkS1p9yRjcy+fWe98H7cjFUrEiYS25p88AHWfXt+ltjt1cuvPknQm/PZ6oF8W/nrc+F+QAaJBXp75hXZcn7fboA5wbDlb4PJzbAh3/umNrE7YsEecZJViu/Q843pcm8RXCLhYc1D1k8Y5RCIv8zcwqUgLEyoFmnjHVcpe2J3lINfYxYVga81twtO22WVDqJY4H71gFhpA+Sf7TgY=
  - secure: aL09BA8HrxjC5jj/zp6yYAJPu2QDIry/Nb43nH1xpY7hSiw+pWO0U2RDv/qpKjv1PBaE70EkFIlsZSHzOL6OPdu3wXMBYjmLgp08DTJWLb7aPHgdSy4tguXvKWHuAB92insEZGobRX0jqchnJ3DjfUWA5ZfBKtqEhShbmQNz4ev/H0hahZzurbIdJF+qe+MYol3EcqwZh27thsXETEgta2nqjrH+/Zj5T6+z2T63LIPZOvFuh1xrcA9YMm300oVbKMjSmSu56AIWEQJb7xJzNtkdcu70xOesqWr8NsWbw2B2jsiCnDKfWdcRv/875mY6l8g1AJm7Rbggngiqf1M8lZ+sUvXNkBMO50fz2R+ksfeizC6ORV0gbFb2yObgrNVsbIZw1/7/lltRFh5GqITM0KEalrW7VisXSViD6vin+4PCCh9xHhIQUr4MFiJwGo4/S5JAkiN8zS1/QRixpcx0J4encMCijGxXucD3427ZrxhwkTxstXQXWZv2QckZ5wIUr/qYZcfuZg9zlWxhHA/Nlk+F6eF7p4TEfOsBvgKlCB1NHTAIPMxTUzaDhpG6Jbzh0hwTmwJzHVH7R7fEDEPvvAsqQJyLTIle1S7KyQ/kwti4RlML0GRf5Faref8PRtABM9tZv07yBd8KycWUlN4BoHinNQw/khmY3hGC9Kn9GGw=
  #- DIST=ubuntu
  #- DIST_REL=xenial
  #- SALT=stable
  matrix:
  - DIST=ubuntu
  - DIST=debian TARGET=saltstack
  - DIST=centos TARGET=saltstack
  #- DIST=debian TARGET=saltmaster
  #- DIST=centos TARGET=saltmaster

script:
  - /bin/true

stages:
- name: test
- name: build
  if: ( branch NOT IN (master) OR fork = true ) AND type IN (push, api, pull_request)
- name: publish
  #if: ( tag =~ ^v.* OR branch IN (master) ) AND type != pull_request AND fork != true
  if: branch IN (master) AND type != pull_request AND fork != true

jobs:
  include:
  - stage: test
# FIXME, use Pipenv instead of pip
    install: &prereq
    - pip install -e "git+https://github.com/avirshup/DockerMake#egg=dockermake"
    - pip install -e "git+https://github.com/pyinvoke/invoke#egg=invoke"
    script:
    - invoke all --dry-targets --filter "{'target':'"$TARGET"', 'salt':'"$SALT"', 'dist':'"$DIST"', 'dist_rel':'"$DIST_REL"', 'formula_rev':'"$FORMULA_REV"'}"
    - invoke all --dry         --filter "{'target':'"$TARGET"', 'salt':'"$SALT"', 'dist':'"$DIST"', 'dist_rel':'"$DIST_REL"', 'formula_rev':'"$FORMULA_REV"'}"
  - stage: build
    install: *prereq
    script:
    # 1st build (build/test)
    - invoke all --filter "{'target':'"$TARGET"', 'salt':'"$SALT"', 'dist':'"$DIST"', 'dist_rel':'"$DIST_REL"', 'formula_rev':'"$FORMULA_REV"'}"
  - stage: publish
    install: *prereq
    script:
    - echo $DOCKER_PASS | docker login --password-stdin -u $DOCKER_USER docker.io/epcim/salt;
    - export PUSH="--push";
    - invoke all --filter "{'target':'"$TARGET"', 'salt':'"$SALT"', 'dist':'"$DIST"', 'dist_rel':'"$DIST_REL"', 'formula_rev':'"$FORMULA_REV"'}" $PUSH ;

after_failure:
- test -e dockerfile.fail && cat dockerfile.fail || true

after_success:
- docker images

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
  email: true

